export interface ReportConfig {
  id: string;
  name: string;
  endpoint: string;
  method: 'GET' | 'POST';
  chartType: 'line' | 'bar' | 'pie';
  inputType: 'none' | 'date' | 'dateRange';
  labelKey: string;
  dataKey: string;
}

export const reportConfigs: ReportConfig[] = [
  {
    id: 'sales-total-by-day',
    name: 'Vendas Totais por Dia',
    endpoint: '/report/sales-total-by-day',
    method: 'POST',
    chartType: 'line',
    inputType: 'dateRange',
    labelKey: 'day',
    dataKey: 'total',
  },
  {
    id: 'revenue-cumulative-by-month',
    name: 'Receita Cumulativa por Mês',
    endpoint: '/report/revenue-cumulative-by-month',
    method: 'POST',
    chartType: 'line',
    inputType: 'dateRange',
    labelKey: 'month',
    dataKey: 'cumulative',
  },
  {
    id: 'sales-by-hour',
    name: 'Vendas por Hora',
    endpoint: '/report/sales-by-hour',
    method: 'POST',
    chartType: 'bar',
    inputType: 'date',
    labelKey: 'hour',
    dataKey: 'total',
  },
  {
    id: 'sales-by-channel',
    name: 'Vendas por Canal',
    endpoint: '/report/sales-by-channel',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'channel',
    dataKey: 'total',
  },
  {
    id: 'avg-ticket-by-day',
    name: 'Ticket Médio por Dia',
    endpoint: '/report/avg-ticket-by-day',
    method: 'POST',
    chartType: 'line',
    inputType: 'dateRange',
    labelKey: 'day',
    dataKey: 'avg',
  },
  {
    id: 'avg-ticket-by-channel',
    name: 'Ticket Médio por Canal',
    endpoint: '/report/avg-ticket-by-channel',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'channel',
    dataKey: 'avg',
  },
  {
    id: 'products-sold-by-day',
    name: 'Produtos Vendidos por Dia',
    endpoint: '/report/products-sold-by-day',
    method: 'POST',
    chartType: 'line',
    inputType: 'dateRange',
    labelKey: 'day',
    dataKey: 'quantity',
  },
  {
    id: 'top-products',
    name: 'Top Produtos',
    endpoint: '/report/top-products',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'name',
    dataKey: 'quantity',
  },
  {
    id: 'sales-by-category',
    name: 'Vendas por Categoria',
    endpoint: '/report/sales-by-category',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'category',
    dataKey: 'quantity',
  },
  {
    id: 'current-stock-by-category',
    name: 'Estoque Atual por Categoria',
    endpoint: '/report/current-stock-by-category',
    method: 'POST',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'category',
    dataKey: 'quantity',
  },
  {
    id: 'clients-registered-by-day',
    name: 'Clientes Registrados por Dia',
    endpoint: '/report/clients-registered-by-day',
    method: 'POST',
    chartType: 'line',
    inputType: 'dateRange',
    labelKey: 'day',
    dataKey: 'count',
  },
  {
    id: 'new-vs-recurring-clients',
    name: 'Novos vs Clientes Recorrentes',
    endpoint: '/report/new-vs-recurring-clients',
    method: 'POST',
    chartType: 'pie',
    inputType: 'dateRange',
    labelKey: 'type',
    dataKey: 'count',
  },
  {
    id: 'orders-by-status',
    name: 'Pedidos por Status',
    endpoint: '/report/orders-by-status',
    method: 'GET',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'status',
    dataKey: 'count',
  },
  {
    id: 'avg-process-step-duration',
    name: 'Duração Média de Etapa',
    endpoint: '/report/avg-process-step-duration',
    method: 'GET',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'process_rule_id',
    dataKey: 'avg_seconds',
  },
  {
    id: 'cancellation-rate',
    name: 'Taxa de Cancelamento',
    endpoint: '/report/cancellation-rate',
    method: 'GET',
    chartType: 'pie',
    inputType: 'none',
    labelKey: 'rate',
    dataKey: 'rate',
  },
  {
    id: 'current-queue-length',
    name: 'Tamanho Atual da Fila',
    endpoint: '/report/current-queue-length',
    method: 'GET',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'length',
    dataKey: 'length',
  },
  {
    id: 'avg-delivery-time-by-driver',
    name: 'Tempo Médio de Entrega por Entregador',
    endpoint: '/report/avg-delivery-time-by-driver',
    method: 'GET',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'driver_id',
    dataKey: 'avg_seconds',
  },
  {
    id: 'deliveries-per-driver',
    name: 'Entregas por Entregador',
    endpoint: '/report/deliveries-per-driver',
    method: 'GET',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'driver_id',
    dataKey: 'count',
  },
  {
    id: 'orders-per-table',
    name: 'Pedidos por Mesa',
    endpoint: '/report/orders-per-table',
    method: 'GET',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'table_id',
    dataKey: 'count',
  },
  {
    id: 'sales-by-shift',
    name: 'Vendas por Turno',
    endpoint: '/report/sales-by-shift',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'shift_id',
    dataKey: 'total',
  },
  {
    id: 'payments-by-method',
    name: 'Pagamentos por Método',
    endpoint: '/report/payments-by-method',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'method',
    dataKey: 'total',
  },
  {
    id: 'sales-by-place',
    name: 'Vendas por Local',
    endpoint: '/report/sales-by-place',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'place',
    dataKey: 'total',
  },
  {
    id: 'sales-by-size',
    name: 'Vendas por Tamanho',
    endpoint: '/report/sales-by-size',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'size',
    dataKey: 'quantity',
  },
  {
    id: 'additional-items-sold',
    name: 'Itens Adicionais Vendidos',
    endpoint: '/report/additional-items-sold',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'name',
    dataKey: 'quantity',
  },
  {
    id: 'avg-pickup-time',
    name: 'Tempo Médio de Coleta',
    endpoint: '/report/avg-pickup-time',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'avg_seconds',
    dataKey: 'avg_seconds',
  },
  {
    id: 'group-items-status',
    name: 'Status de Itens de Grupo',
    endpoint: '/report/group-items-status',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'status',
    dataKey: 'count',
  },
  {
    id: 'deliveries-by-cep',
    name: 'Entregas por CEP',
    endpoint: '/report/deliveries-by-cep',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'cep',
    dataKey: 'count',
  },
  {
    id: 'processed-count-by-rule',
    name: 'Processados por Regra',
    endpoint: '/report/processed-count-by-rule',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'rule_id',
    dataKey: 'count',
  },
  {
    id: 'employee-payments-report',
    name: 'Pagamentos de Funcionários',
    endpoint: '/report/employee-payments-report',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'employee_id',
    dataKey: 'total',
  },
  // Top 10 mesas mais utilizadas
  {
    id: 'top-tables',
    name: 'Top 10 Mesas',
    endpoint: '/report/top-tables',
    method: 'POST',
    chartType: 'bar',
    inputType: 'dateRange',
    labelKey: 'table_id',
    dataKey: 'count',
  },
  // Queue and process metrics
  {
    id: 'avg-queue-duration',
    name: 'Duração Média da Fila',
    endpoint: '/report/avg-queue-duration',
    method: 'GET',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'avg_seconds',
    dataKey: 'avg_seconds',
  },
  {
    id: 'avg-process-duration-by-product',
    name: 'Duração Média por Produto',
    endpoint: '/report/avg-process-duration-by-product',
    method: 'GET',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'product_name',
    dataKey: 'avg_seconds',
  },
  {
    id: 'total-queue-time-by-group-item',
    name: 'Tempo Total de Fila por Item de Grupo',
    endpoint: '/report/total-queue-time-by-group-item',
    method: 'GET',
    chartType: 'bar',
    inputType: 'none',
    labelKey: 'group_item_id',
    dataKey: 'total_seconds',
  },
];